export const RESPONSE_SUCCESS_CODE = {
  Success: 0,
  Failure: 1,
};

export const HANDLER_IDS = {
  INITIAL_USER: 0,
  CONNECTED_USERS: 1,
  LOBBY_CHAT: 2,
  CREATE_ROOM: 3,
  START_ACK: 4,
  USER_START: 30,
  UPDATE_POSITION: 31,
  UPDATE_ANIMATION: 32,
  INITIAL_ENTITY: 33,
  DELETE_ENTITY: 34,
  DELETE_USER: 35,
};
