export const RESPONSE_SUCCESS_CODE = {
  Success: 0,
  Failure: 1,
};

export const HANDLER_IDS = {
  INITIAL_USER: 0,
  CONNECTED_USERS: 1,
  LOBBY_CHAT: 2,
  CREATE_ROOM: 3,
  START_ACK:4,
  FIRST_CONNECTION_CHECK:24,
  CREATE_GAME: 45,
  JOIN_GAME: 55,
  UPDATE_LOCATION: 56,
};
